[env:pico2]
; Sử dụng platform hỗ trợ RP2350 (Pico 2) mới nhất
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpi_pico2
framework = picosdk

; Cấu hình UART tốc độ cao
monitor_speed = 115200
