// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// ir_carrier //
// ---------- //

#define ir_carrier_wrap_target 0
#define ir_carrier_wrap 11
#define ir_carrier_pio_version 0

#define ir_carrier_offset_entry 0u

static const uint16_t ir_carrier_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0
    0x603f, //  1: out    x, 31           side 0
    0x6041, //  2: out    y, 1            side 0
    0x0068, //  3: jmp    !y, 8           side 0
    0xb142, //  4: nop                    side 1 [1]
    0xa042, //  5: nop                    side 0
    0x0044, //  6: jmp    x--, 4          side 0
    0x0000, //  7: jmp    0               side 0
    0xa142, //  8: nop                    side 0 [1]
    0xa042, //  9: nop                    side 0
    0x0048, // 10: jmp    x--, 8          side 0
    0x0000, // 11: jmp    0               side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program ir_carrier_program = {
    .instructions = ir_carrier_program_instructions,
    .length = 12,
    .origin = -1,
    .pio_version = ir_carrier_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config ir_carrier_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ir_carrier_wrap_target, offset + ir_carrier_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void ir_carrier_program_init(PIO pio, uint sm, uint offset, uint pin) {
    pio_sm_config c = ir_carrier_program_get_default_config(offset);
    // Cấu hình chân side-set (chân phát LED IR)
    sm_config_set_sideset_pins(&c, pin);
    // Cấu hình GPIO cho chân này chịu sự điều khiển của PIO
    pio_gpio_init(pio, pin);
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Cấu hình clock divider để đạt tần số 152,000 Hz (4 * 38,000)
    // Tần số hệ thống RP2350 đã được ép xung lên 300MHz (300,000,000 Hz)
    float div = 300000000.0f / 152000.0f;
    sm_config_set_clkdiv(&c, div);
    // Khởi tạo State Machine
    pio_sm_init(pio, sm, offset, &c);
    // Bật State Machine
    pio_sm_set_enabled(pio, sm, true);
}

#endif

