[env:esp32-c5-devkitc-1]
platform = espressif32
board = esp32-c5-devkitc-1
framework = espidf

monitor_speed = 115200

; Tối ưu hóa PSRAM 8MB (Octal SPIRAM) cho dòng C5 N16R8
board_build.arduino.memory_type = qio_qspi
board_build.partitions = huge_app.csv
build_flags = 
    -DBOARD_HAS_PSRAM

