[env:esp32-c6-devkitc-1]
platform = espressif32
board = esp32-c6-devkitc-1
framework = espidf

monitor_speed = 115200

; Tăng dung lượng bộ nhớ cấp phát tĩnh nếu cần dùng nhiều RAM cho SSH
board_build.partitions = huge_app.csv
